const { withAndroidStyles, AndroidConfig } = require('expo/config-plugins');

/**
 * Makes the Android system navigation bar show the app's own background instead of a
 * grey band.
 *
 * `edgeToEdgeEnabled` in app.json pulls in react-native-edge-to-edge, whose
 * `Theme.EdgeToEdge` already sets `android:navigationBarColor` to transparent on API 27+.
 * The band that remains is the platform's contrast scrim: that theme also sets
 * `enforceNavigationBarContrast` to `true`, which on API 29+ makes Android paint a
 * translucent backdrop behind the bar so system gesture/button affordances stay legible.
 * Turning it off is what actually lets the app background through.
 *
 * This lives in a config plugin rather than as a hand edit to
 * `android/app/src/main/res/values/styles.xml` because that directory is gitignored and
 * regenerated by `expo prebuild`, which would silently drop the change.
 */
module.exports = function withTransparentNavigationBar(config) {
  return withAndroidStyles(config, (cfg) => {
    const parent = { name: 'AppTheme', parent: 'Theme.EdgeToEdge' };

    cfg.modResults = AndroidConfig.Styles.assignStylesValue(cfg.modResults, {
      add: true,
      parent,
      name: 'enforceNavigationBarContrast',
      value: 'false',
    });

    // Belt and braces for API 26 and below, where the library's default
    // navigationBarColor is a semi-transparent dark (#801b1b1b) rather than clear.
    cfg.modResults = AndroidConfig.Styles.assignStylesValue(cfg.modResults, {
      add: true,
      parent,
      name: 'android:navigationBarColor',
      value: '@android:color/transparent',
    });

    return cfg;
  });
};
